# Form implementation generated from reading ui file '/home/scoiaz/python/ericWS/Xmonitor/Xmon.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(861, 650)
        self.centralWidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.tabWidget = QtWidgets.QTabWidget(parent=self.centralWidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 841, 631))
        self.tabWidget.setObjectName("tabWidget")
        self.tab1 = QtWidgets.QWidget()
        self.tab1.setObjectName("tab1")
        self.textOutput = QtWidgets.QTextEdit(parent=self.tab1)
        self.textOutput.setGeometry(QtCore.QRect(20, 350, 571, 231))
        self.textOutput.setObjectName("textOutput")
        self.listOutput = QtWidgets.QListWidget(parent=self.tab1)
        self.listOutput.setGeometry(QtCore.QRect(20, 40, 571, 301))
        self.listOutput.setObjectName("listOutput")
        self.label = QtWidgets.QLabel(parent=self.tab1)
        self.label.setGeometry(QtCore.QRect(21, 14, 41, 20))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.tab1)
        self.label_2.setGeometry(QtCore.QRect(458, 14, 41, 20))
        self.label_2.setObjectName("label_2")
        self.btnGo = QtWidgets.QPushButton(parent=self.tab1)
        self.btnGo.setGeometry(QtCore.QRect(550, 10, 41, 26))
        self.btnGo.setObjectName("btnGo")
        self.txtCmd = QtWidgets.QLineEdit(parent=self.tab1)
        self.txtCmd.setGeometry(QtCore.QRect(60, 10, 391, 26))
        self.txtCmd.setObjectName("txtCmd")
        self.txtRows = QtWidgets.QLineEdit(parent=self.tab1)
        self.txtRows.setGeometry(QtCore.QRect(500, 10, 41, 26))
        self.txtRows.setObjectName("txtRows")
        self.tabWidget.addTab(self.tab1, "")
        self.tab2 = QtWidgets.QWidget()
        self.tab2.setObjectName("tab2")
        self.graphicsView = QtWidgets.QGraphicsView(parent=self.tab2)
        self.graphicsView.setGeometry(QtCore.QRect(10, 10, 817, 581))
        self.graphicsView.setObjectName("graphicsView")
        self.tabWidget.addTab(self.tab2, "")
        MainWindow.setCentralWidget(self.centralWidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Flags"))
        self.label_2.setText(_translate("MainWindow", "Rows"))
        self.btnGo.setText(_translate("MainWindow", "Go"))
        self.txtCmd.setText(_translate("MainWindow", "-sn"))
        self.txtRows.setText(_translate("MainWindow", "5"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab1), _translate("MainWindow", "Control"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab2), _translate("MainWindow", "Graph"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
