# Form implementation generated from reading ui file '/home/scoiaz/python/ericWS/Xmonitor/Xmon.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(869, 654)
        self.centralWidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.graphicsView = QtWidgets.QGraphicsView(parent=self.centralWidget)
        self.graphicsView.setGeometry(QtCore.QRect(590, 10, 256, 192))
        self.graphicsView.setObjectName("graphicsView")
        self.textOutput = QtWidgets.QTextEdit(parent=self.centralWidget)
        self.textOutput.setGeometry(QtCore.QRect(10, 380, 571, 231))
        self.textOutput.setObjectName("textOutput")
        self.txtCmd = QtWidgets.QLineEdit(parent=self.centralWidget)
        self.txtCmd.setGeometry(QtCore.QRect(10, 10, 521, 26))
        self.txtCmd.setObjectName("txtCmd")
        self.btnGo = QtWidgets.QPushButton(parent=self.centralWidget)
        self.btnGo.setGeometry(QtCore.QRect(540, 10, 41, 26))
        self.btnGo.setObjectName("btnGo")
        self.listOutput = QtWidgets.QListWidget(parent=self.centralWidget)
        self.listOutput.setGeometry(QtCore.QRect(10, 40, 571, 331))
        self.listOutput.setObjectName("listOutput")
        MainWindow.setCentralWidget(self.centralWidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.txtCmd.setText(_translate("MainWindow", "-sn"))
        self.btnGo.setText(_translate("MainWindow", "Go"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
